sudo: required
dist: trusty
language: ruby
rvm:
  - 2.2
  - 2.3

gemfile:
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile

before_install:
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E0C56BD4
  - echo "deb http://repo.yandex.ru/clickhouse/trusty stable main" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install clickhouse-client clickhouse-server-common -y
  - sudo service clickhouse-server start
  - gem install bundler

notifications:
  email:
    on_success: change # only send if status change
